name: Add text

on:
  push:
    branches: main

jobs:
  fetch:
    name: Add text
    runs-on: ubuntu-latest

    steps:
      - name: Git config set
        run: |
          git config --global core.autocrlf input
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Git config show
        run: "git config --local -l"

      - name: Git pull
        run: "git pull origin main"
      
      # - name: Git config unset
      #   run: |
      #     git config --local --unset user.signingkey
      #     git config --local --unset gpg.format
      #     git config --local --unset gpg.ssh.program
      #     git config --local --unset commit.gpgsign

      - name: Add text
        run: |
          cat ./data/data.txt | sed '$ahoge'

      - name: Git
        run: |
          git add ./data/data.txt
          git commit -m "Add text" || echo "No changes to commit"
          git push origin main